services:
  backend:
    build:
      context: .
    command: python ./server/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.node
      target: development
    command: npm run dev
    environment:
      - LOCAL_URL='backend:8000/';
    ports:
      - 3004:5173
    volumes:
      - ./app:/app/app
    depends_on:
      - backend
  
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile.node
      target: production
    ports:
      - 3004:80
    volumes:
      - ./app:/app/app
    depends_on:
      - backend
