services:
  backend:
    build:
      context: .
    container_name: backend_c
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.node
      # target: development
    container_name: frontend_c_dev
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    stdin_open: true
    tty: true
  
  # frontend-prod:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.node
  #     target: production
  #   ports:
  #     - 3004:80
  #   volumes:
  #     - ./app:/app/frontend
  #   depends_on:
  #     - backend